---
openapi: 3.0.1
info:
  title: Indoor Navigation API
  description: This is the interface for communicating with the Indoor Navigation service.
  version: "1.0"
paths:
  /node:
    get:
      tags:
        - node
      summary: Returns a list of nodes
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
    post:
      tags:
        - node
      summary: Create a new node
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        400:
          description: Node not valid, return violations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  /node/{name}:
    get:
      tags:
        - node
      summary: Returns a node with the sepcified name
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        404:
          description: Node with the specified name does not exist
    put:
      tags:
        - node
      summary: Update the node with the specified name
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Node'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        400:
          description: Node is not valid
        404:
          description: Node with the specified name does not exist
    delete:
      tags:
        - node
      summary: Delete the node with the specified name
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
        404:
          description: Node with the specified name does not exist
  /path/shortest:
    get:
      tags:
        - path
      summary: Return the shortest path from start to end
      parameters:
      - name: end
        in: query
        required: true
        schema:
          type: string
      - name: start
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeDistance'
        400:
          description: Start or end name are empty
        404:
          description: Nodes with the specified start and end name do not exist
  /path/handicapped:
    get:
      tags:
        - path
      summary: Return the shortest path from start to end for handicapped people
      parameters:
        - name: end
          in: query
          required: true
          schema:
            type: string
        - name: start
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeDistance'
        400:
          description: Start or end name are empty
        404:
          description: Nodes with the specified start and end name do not exist
  /relationship:
    post:
      tags:
        - relationship
      summary: Create relationship between start and end node
      parameters:
      - name: end
        in: query
        required: true
        schema:
          type: string
          nullable: false
      - name: start
        in: query
        required: true
        schema:
          type: string
          nullable: false
      responses:
        200:
          description: Created relationship
        404:
          description: Start and/or end node with the specified name does not exist
    delete:
      tags:
        - relationship
      summary: Delete relationship between two specified names
      parameters:
      - name: end
        in: query
        required: true
        schema:
          type: string
          nullable: false
      - name: start
        in: query
        required: true
        schema:
          type: string
          nullable: false
      responses:
        200:
          description: OK
        404:
          description: Nodes with the specified start and end name do not exist
components:
  schemas:
    NodeType:
      enum:
      - ELEVATOR
      - FLOOR
      - STAIRS
      type: string
    Node:
      required:
      - isHidden
      - type
      - x
      - y
      - z
      type: object
      properties:
        id:
          format: int64
          type: integer
        isHidden:
          type: boolean
          nullable: false
        name:
          pattern: \S
          type: string
          nullable: false
        type:
          allOf:
            - $ref: '#/components/schemas/NodeType'
          nullable: false
        x:
          format: float
          type: number
          nullable: false
        y:
          format: float
          type: number
          nullable: false
        z:
          format: float
          type: number
          nullable: false
    NodeDistance:
      type: object
      properties:
        node:
          $ref: '#/components/schemas/Node'
        distance:
          format: float
          type: number
    FailedField:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        message:
          type: string
    Result:
      type: object
      properties:
        isSuccessful:
          type: boolean
        failedFields:
          type: array
          items:
            $ref: '#/components/schemas/FailedField'
